# Generated by Django 5.1.6 on 2025-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_max_alternatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project_count',
            field=models.IntegerField(default=0, help_text='Number of projects created by this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_alternative_count',
            field=models.IntegerField(default=0, help_text='Total alternatives created across all projects'),
        ),
    ]
