# Generated by Django 5.1.6 on 2025-08-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_counter_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_alternatives',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_alternative_count',
        ),
    ]
