# Generated by Django 5.1.6 on 2025-07-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_api', '0003_fix_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahpproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='ahpproject',
            table='ahp_api_ahpproject',
        ),
    ]
