# Generated by Django 5.1.6 on 2025-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp_api', '0004_alter_ahpproject_options_alter_ahpproject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahpproject',
            name='alternative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ahpproject',
            name='alternative_limit',
            field=models.IntegerField(default=3),
        ),
    ]
